### ISSUE TITLE
Project does not build properly

### ISSUE THREAD

**Issue by SumonGFC** [MatMercer/ncurses-space-invaders#1]
Hello,
Unfortunately, this project does not build correctly on my machine. when I run `make`, I get a long list of "undefined reference to X" errors during the linking phase. For example:

`/usr/bin/ld: spcinv.c:(.text+0x2c): undefined reference to 'initscr'`     (I have ncurses headers in my /usr/share)

and
`/usr/bin/ld: spcinv.c:(.text+0xf6): undefined reference to PLAYER_POS'` (undefined references for basically all your definitions in spcinv.h)

There are quite a lot of them, I think one for each reference in spcinv.h. I do not know much about C or Make or linking (I am new to programming in general), and I do not know how to resolve this issue. Any help would be appreciated, I can provide more information if you have the patience and would like to resolve this issue.

**Comment by MatMercer** [comment]
Hey! It was a surprise to have an issue opened in my college project!

I fixed it for you, seems like compilers/linkers nowadays requires you to define `extern` vars into `.c` files. This project was written in 2017.

Try now, I updated the .gif at README too, and thx!

**Comment by scriabin-enjoyer** [comment]
Hello, I am the OP of this issue. Sorry for taking so long getting back to you, and thank you for helping me! I believe that some of my linker errors were solved by the `// Define global variables` fix. However, it seems that my machine is still unable to link the binaries. In particular, it seems that my linker is unable to link the actual ncurses library. Below you can see all the linker errors. As you can see, these are all ncurses functions.
<details>
<summary>My Linker Errors</summary>

```bash
[ 50%] Linking C static library lib/libspcinv.a
[ 50%] Built target spcinv
[ 75%] Building C object CMakeFiles/ncurses-space-invaders.dir/src/main.c.o
[100%] Linking C executable bin/ncurses-space-invaders
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): warning: relocation against `stdscr' in read-only section `.text'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `initGame':
spcinv.c:(.text+0x2c): undefined reference to `initscr'
/usr/bin/ld: spcinv.c:(.text+0x31): undefined reference to `noecho'
/usr/bin/ld: spcinv.c:(.text+0x3b): undefined reference to `curs_set'
/usr/bin/ld: spcinv.c:(.text+0x42): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x4f): undefined reference to `keypad'
/usr/bin/ld: spcinv.c:(.text+0x56): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x63): undefined reference to `nodelay'
/usr/bin/ld: spcinv.c:(.text+0x68): undefined reference to `start_color'
/usr/bin/ld: spcinv.c:(.text+0x6f): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x81): undefined reference to `wattr_on'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `render':
spcinv.c:(.text+0x533): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x53b): undefined reference to `werase'
/usr/bin/ld: spcinv.c:(.text+0x55f): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x597): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x5c6): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x605): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x652): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x681): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x689): undefined reference to `wrefresh'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `getPressedKey':
spcinv.c:(.text+0x6ed): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x6f5): undefined reference to `wgetch'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `getWinSize':
spcinv.c:(.text+0x73e): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x74a): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x766): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x772): undefined reference to `stdscr'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `drawBorder':
spcinv.c:(.text+0x7d4): undefined reference to `init_pair'
/usr/bin/ld: spcinv.c:(.text+0x7e8): undefined reference to `init_pair'
/usr/bin/ld: spcinv.c:(.text+0x8ca): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x8dc): undefined reference to `wattr_on'
/usr/bin/ld: spcinv.c:(.text+0x8f3): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x905): undefined reference to `wattr_on'
/usr/bin/ld: spcinv.c:(.text+0x915): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x927): undefined reference to `wattr_on'
/usr/bin/ld: spcinv.c:(.text+0x950): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x96e): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x9a6): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x9c4): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x9da): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x9ec): undefined reference to `wattr_off'
/usr/bin/ld: spcinv.c:(.text+0x9f3): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0xa05): undefined reference to `wattr_off'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `drawPlayer':
spcinv.c:(.text+0xa24): undefined reference to `init_pair'
/usr/bin/ld: spcinv.c:(.text+0xa2b): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0xa3d): undefined reference to `wattr_on'
/usr/bin/ld: spcinv.c:(.text+0xa5e): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0xa82): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0xa89): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0xa9b): undefined reference to `wattr_off'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `drawAliens':
spcinv.c:(.text+0xabe): undefined reference to `init_pair'
/usr/bin/ld: spcinv.c:(.text+0xac5): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0xad7): undefined reference to `wattr_on'
/usr/bin/ld: spcinv.c:(.text+0xb7b): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0xbde): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0xc0f): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0xc21): undefined reference to `wattr_off'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `drawLasers':
spcinv.c:(.text+0xc61): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0xcad): undefined reference to `mvprintw'
/usr/bin/ld: lib/libspcinv.a(spcinv.c.o): in function `gameOver':
spcinv.c:(.text+0x1c32): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x1c3a): undefined reference to `werase'
/usr/bin/ld: spcinv.c:(.text+0x1c83): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x1c9e): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x1cbc): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x1cda): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x1cf8): undefined reference to `mvprintw'
/usr/bin/ld: spcinv.c:(.text+0x1dad): undefined reference to `stdscr'
/usr/bin/ld: spcinv.c:(.text+0x1db5): undefined reference to `wrefresh'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ncurses-space-invaders.dir/build.make:99: bin/ncurses-space-invaders] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/ncurses-space-invaders.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
</details>

UPDATE: After several hours of banging my head against this problem, I finally found a solution. I added a `-lncurses` flag to the final command in CMakeLists.txt (line 25):
```c
target_link_libraries(ncurses-space-invaders ${CURSES_LIBRARY} spcinv -lncurses)
```
After this, the project was able to link successfully, and I was able to play the game. I'm not exactly sure why I had to add this linker flag explicitly (because I have no idea how the linking phase "works", just that you have to somehow mash together all the disparate object files/binaries at the end.)

Anyways, thanks again for all your help. If you would like, you can ask me some questions about my system if you would like to find out why ncurses wasn't linking on my machine. Otherwise, feel free to close this issue (I would close it, but I forgot my password to my old account).

**Comment by MatMercer** [comment]
Its. Fixed!
